# Generated by Django 4.2.2 on 2023-06-29 18:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Время создание ')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Время изменения')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('start', models.DateField(verbose_name='Начало активности')),
                ('end', models.DateField(verbose_name='Конец активности')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Уровень')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Время создание ')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Время изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Время создание ')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Время изменения')),
                ('index', models.CharField(max_length=250, verbose_name='Индекс')),
                ('name', models.TextField(max_length=250, verbose_name='Наименование')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
                ('form_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Форма')),
            ],
        ),
        migrations.CreateModel(
            name='FilesCatigories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Inspectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Время создание ')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Время изменения')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250, verbose_name='Значение')),
                ('table_name', models.CharField(max_length=250, null=True, verbose_name='Название таблицы')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Время создание ')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Время изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Время создание ')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Время изменения')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingPeriods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('active', models.BooleanField(verbose_name='Активная')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Время создание ')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Время изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('display_name', models.CharField(max_length=250, verbose_name='Название дисплея')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Время создание ')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Время изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Время создание ')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Время изменения')),
                ('table_name', models.CharField(max_length=250, verbose_name='Название')),
                ('column_name', models.CharField(max_length=250, verbose_name='Название столбцов ')),
                ('foreign_key', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Связь')),
                ('locale', models.CharField(max_length=250, verbose_name='Локация')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Время создание ')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Время изменения')),
                ('objectguid', models.CharField(max_length=250, null=True, verbose_name='objectguid')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('avatar', models.CharField(max_length=250, null=True, verbose_name='avatar')),
                ('password', models.CharField(max_length=250, verbose_name='Пароль')),
                ('remember_token', models.IntegerField(verbose_name='remember_token')),
                ('settings', models.TextField(null=True, verbose_name='Настройки')),
                ('username', models.CharField(max_length=250, verbose_name='Имя пользователя')),
                ('orcid', models.CharField(max_length=250, null=True, verbose_name='orcid')),
                ('worsrid', models.CharField(max_length=250, null=True, verbose_name='worsrid')),
                ('said', models.CharField(max_length=250, null=True, verbose_name='Оценка')),
                ('spin', models.CharField(max_length=250, null=True, verbose_name='spin')),
                ('department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_OETD.departments')),
                ('inspector_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_OETD.inspectors')),
                ('position_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_OETD.positions')),
            ],
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Время создание ')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Время изменения')),
                ('value', models.TextField(null=True, verbose_name='Значение')),
                ('lock', models.BooleanField(verbose_name='Допуск')),
                ('comment', models.TextField(null=True, verbose_name='Комментарий')),
                ('visible', models.BooleanField(verbose_name='Видимый')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_OETD.categories')),
                ('field_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_OETD.fields')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_OETD.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_OETD.roles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_OETD.users')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_OETD.permissions')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_OETD.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Menuitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('url', models.CharField(max_length=250, verbose_name='urls')),
                ('target', models.CharField(max_length=250, verbose_name='Цель')),
                ('icon_class', models.CharField(max_length=250, null=True, verbose_name='Класс иконки')),
                ('color', models.CharField(max_length=250, null=True, verbose_name='Цвет')),
                ('parent_id', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Родительский id')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='order')),
                ('route', models.CharField(max_length=250, null=True, verbose_name='Route')),
                ('parameters', models.TextField(null=True, verbose_name='Параметры')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Время создание ')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Время изменения')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_OETD.menus')),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Время создание ')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Время изменения')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('commentable', models.IntegerField(verbose_name='commentable')),
                ('reporting_period_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_OETD.reportingperiods')),
            ],
        ),
        migrations.CreateModel(
            name='FormReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_OETD.forms')),
                ('reporting_period_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_OETD.reportingperiods')),
            ],
        ),
        migrations.CreateModel(
            name='FormPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_OETD.forms')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_OETD.positions')),
            ],
        ),
        migrations.CreateModel(
            name='FormCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_OETD.categories')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_OETD.forms')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Время создание ')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Время изменения')),
                ('path', models.CharField(max_length=250, verbose_name='Путь')),
                ('name', models.TextField(max_length=250, verbose_name='Наименование')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
                ('file_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_OETD.filescatigories')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_OETD.users')),
            ],
        ),
        migrations.AddField(
            model_name='fields',
            name='inspector_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_OETD.inspectors'),
        ),
    ]
