# Generated by Django 4.2.2 on 2023-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_OETD", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="end",
            field=models.DateTimeField(verbose_name="Конец активности"),
        ),
        migrations.AlterField(
            model_name="category",
            name="start",
            field=models.DateTimeField(verbose_name="Начало активности"),
        ),
    ]
