from django.contrib import admin
from .models import *
admin.site.register(Permissions)
admin.site.register(Departments)
admin.site.register(Users)
admin.site.register(PermissionRole)
admin.site.register(Positions)
admin.site.register(ReportingPeriods)
admin.site.register(Fields)
admin.site.register(MenuItems)
admin.site.register(Categories)
admin.site.register(Forms)
admin.site.register(Files)
admin.site.register(Roles)
admin.site.register(FilesCatigories)
admin.site.register(FormCategory)
admin.site.register(FormPosition)
admin.site.register(FormReportingPeriod)
admin.site.register(Inspectors)
admin.site.register(Translations)
admin.site.register(Menus)
admin.site.register(UserRoles)
admin.site.register(Values)

